name: Deploy to Hostinger
on:
  workflow_run:
    workflows: ["Test Laravel"]
    types:
      - completed

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
  SSH_PORT: ${{ vars.SSH_PORT }}
  SSH_USER: ${{ vars.SSH_USER }}
  SSH_IP: ${{ vars.SSH_IP }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH Directory
        run: mkdir ~/.ssh

      - name: Install SSH Private Key
        run: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa

      - name: Permissions for SSH Private Key
        run: chmod 600 ~/.ssh/id_rsa

      - name: Install SSH Known Hosts
        run: echo $SSH_KNOWN_HOSTS > ~/.ssh/known_hosts

      - name: Git Pull
        run: ssh -p $SSH_PORT $SSH_USER@$SSH_IP 'cd ~/github/laravel-crud && git pull;'

      - name: Composer Install
        run: ssh -p $SSH_PORT $SSH_USER@$SSH_IP 'cd ~/github/laravel-crud && /opt/alt/php82/usr/bin/php ~/composer.phar install --no-dev --prefer-dist --no-ansi --no-interaction --no-progress;'

      - name: Artisan Migrate
        run: ssh -p $SSH_PORT $SSH_USER@$SSH_IP 'cd ~/github/laravel-crud && /opt/alt/php82/usr/bin/php artisan migrate:fresh --force'
